### ISSUE TITLE
swoole加密高版本

### ISSUE THREAD

**Issue by MENC-JIAMI** [Jader/CodeEncryption#2]
有7.3-8.1的包吗

**Comment by Jader** [comment]
Swoole-Compiler 是支持的 7.3的， CodeEncryption 封装的镜像是不支持7.3的，CodeEncryption 里面用的是 Swoole-Compiler 7.2的扩展，Swoole-Compiler 7.3的可以去 Swoole 官方了解

**Comment by Jader** [comment]
> 有7.3-8.1的包吗

Swoole-Compiler 7.3的CodeEncryption是去支持的镜像，是不支持7.3的，CodeEncryption里面用的是Swoole-Compiler 7.2的扩展，Swoole-Compiler 7.3的可以官方了解

**Comment by Jader** [comment]
> 有7.3-8.1的包吗

Swoole-Compiler 7.3的CodeEncryption是去支持的镜像，是不支持7.3的，CodeEncryption里面用的是Swoole-Compiler 7.2的扩展，Swoole-Compiler 7.3的可以官方了解
